/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.jmultidiskzip.ui.gui;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public class CreateDialog extends javax.swing.JDialog {

    private boolean auto = false;
    
    public CreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public CreateDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        outputFileField = new javax.swing.JTextField();
        outputFileButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        encryptWithAPassword = new javax.swing.JCheckBox();
        passwordField = new javax.swing.JPasswordField();
        showPasswordField = new javax.swing.JCheckBox();
        randomCharactersLabel = new javax.swing.JLabel();
        randomCharacters = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create");
        setIconImage(new ImageIcon(MainWindow.class.getResource("create.png")).getImage());
        setMinimumSize(new java.awt.Dimension(200, 400));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input files (Drag and drop supported)"));

        fileList.setModel(new DefaultListModel<String>()
        );
        this.fileList.setTransferHandler(new FileDragAndDrop() {
            @Override
            protected boolean process(List<File> files) {
                DefaultListModel<String> model = (DefaultListModel<String>) fileList.getModel();
                for (File f:files) {
                    String s = f.toString();
                    if (!model.contains(s)) {
                        model.addElement(s);
                    }
                }
                return true;
            }
        });
        jScrollPane1.setViewportView(fileList);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addButton)
                        .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(clearButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output file"));

        outputFileField.setEditable(false);

        outputFileButton.setText("...");
        outputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputFileField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputFileButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFileButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createButton.setText("Create");
        createButton.setEnabled(false);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        encryptWithAPassword.setText("Encrypt with a password:");
        encryptWithAPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptWithAPasswordActionPerformed(evt);
            }
        });

        passwordField.setEnabled(false);

        showPasswordField.setText("Show");
        showPasswordField.setEnabled(false);
        showPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordFieldActionPerformed(evt);
            }
        });

        randomCharactersLabel.setText("Type random characters below:");
        randomCharactersLabel.setEnabled(false);

        randomCharacters.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomCharacters)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(settingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPasswordField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encryptWithAPassword)
                            .addComponent(randomCharactersLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptWithAPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomCharactersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(settingsButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setMultiSelectionEnabled(true);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File[] files = chooser.getSelectedFiles();
            DefaultListModel<String> model = (DefaultListModel<String>) this.fileList.getModel();
            for (int i = 0; i < files.length; i++) {
                String element = files[i].toString();
                if (!model.contains(element)) {
                    model.addElement(element);
                }
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int[] selected = this.fileList.getSelectedIndices();
        String[] toRemove = new String[selected.length];
        for (int i = 0; i < selected.length; i++) {
            toRemove[i] = this.fileList.getModel().getElementAt(selected[i]);
        }
        for (String s : toRemove) {
            ((DefaultListModel<String>) this.fileList.getModel()).removeElement(s);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        ((DefaultListModel<String>) this.fileList.getModel()).clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        SettingsDialog dialog = new SettingsDialog(this, true);
        dialog.selectCreateTab();
        dialog.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void outputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (this.fileList.getModel().getSize() != 0) {
            File file = new File(this.fileList.getModel().getElementAt(0));
            if (file.getParentFile() != null) {
                chooser.setCurrentDirectory(file.getParentFile());
            } else {
                chooser.setCurrentDirectory(file);
            }
        }
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = chooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            this.outputFileField.setText(chooser.getSelectedFile().toString());
            this.createButton.setEnabled(true);
        }
    }//GEN-LAST:event_outputFileButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        byte[] salt = null;
        char[] password = null;
        if (this.encryptWithAPassword.isSelected()) {
            salt = this.randomCharacters.getText().getBytes(StandardCharsets.UTF_8);
            password = this.passwordField.getPassword();
            if (password.length == 0) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Password is empty", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        CreateOperation operation;
        try {
            this.passwordField.setText("");
            DefaultListModel<String> model = (DefaultListModel<String>) this.fileList.getModel();

            Path outputFile = Path.of(this.outputFileField.getText());
            Path[] inputFiles = new Path[model.size()];
            for (int i = 0; i < inputFiles.length; i++) {
                inputFiles[i] = Path.of(model.elementAt(i));
            }

            CreateOperationSettings settings = new CreateOperationSettings();
            settings.load();
            CreateOperationData data = new CreateOperationData(settings, outputFile, inputFiles, salt, password);
            try {
                if (getParent() instanceof Dialog d) {
                    operation = new CreateOperation(data, d, true);
                } else if (getParent() instanceof Frame f) {
                    operation = new CreateOperation(data, f, true);
                } else {
                    operation = new CreateOperation(data, (Frame) null, true);
                }
            } finally {
                data.clearPassword();
            }
        } finally {
            if (password != null) {
                Arrays.fill(password, '\0');
            }
        }

        setVisible(false);
        dispose();

        if (this.auto) {
            operation.setCloseAfterFinishEnabled(true);
        }
        operation.start();
        operation.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    private void encryptWithAPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptWithAPasswordActionPerformed
        boolean enabled = this.encryptWithAPassword.isSelected();
        this.passwordField.setEnabled(enabled);
        this.showPasswordField.setEnabled(enabled);
        this.randomCharactersLabel.setEnabled(enabled);
        this.randomCharacters.setEnabled(enabled);
    }//GEN-LAST:event_encryptWithAPasswordActionPerformed

    private void showPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordFieldActionPerformed
        if (this.showPasswordField.isSelected()) {
            this.passwordField.setEchoChar('\0');
        } else {
            this.passwordField.setEchoChar(new JPasswordField().getEchoChar());
        }
    }//GEN-LAST:event_showPasswordFieldActionPerformed

    protected void auto(Path[] input, Path output) {
        DefaultListModel<String> model = (DefaultListModel<String>) this.fileList.getModel();
        for (int i = 0; i < input.length; i++) {
            String element = input[i].toString();
            if (!model.contains(element)) {
                model.addElement(element);
            }
        }
        this.outputFileField.setText(output.toString());
        this.createButton.setEnabled(true);
        this.auto = true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton createButton;
    private javax.swing.JCheckBox encryptWithAPassword;
    private javax.swing.JList<String> fileList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton outputFileButton;
    private javax.swing.JTextField outputFileField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField randomCharacters;
    private javax.swing.JLabel randomCharactersLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JCheckBox showPasswordField;
    // End of variables declaration//GEN-END:variables
}
