/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.jmultidiskzip.ui.gui;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public class ExtractDialog extends javax.swing.JDialog {
    
    private boolean auto = false;
    
    public ExtractDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public ExtractDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    private void checkIfExtractShouldBeEnabled() {
        if (!this.inputFile.getText().isEmpty() && !this.outputDirectory.getText().isEmpty()) {
            this.extractButton.setEnabled(true);
        }
    }
    
    private void setInputFile(File file) {
        this.inputFile.setText(file.toString());
        checkIfExtractShouldBeEnabled();
    }
    
    private void setOutputDirectory(File file) {
        this.outputDirectory.setText(file.toString());
        checkIfExtractShouldBeEnabled();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputFile = new javax.swing.JTextField();
        inputFileButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        outputDirectory = new javax.swing.JTextField();
        outputDirectoryButton = new javax.swing.JButton();
        decryptWithAPassword = new javax.swing.JCheckBox();
        passwordField = new javax.swing.JPasswordField();
        showPasswordField = new javax.swing.JCheckBox();
        extractButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Extract");
        setIconImage(new ImageIcon(MainWindow.class.getResource("open.png")).getImage());
        setMinimumSize(new java.awt.Dimension(200, 260));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input file (Drag and drop supported)"));

        inputFile.setEditable(false);
        this.inputFile.setTransferHandler(new FileDragAndDrop() {
            @Override
            public boolean process(List<File> files) {
                File first = files.get(0);
                if (first.isFile()) {
                    setInputFile(first);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
                return true;
            }
        });

        inputFileButton.setText("...");
        inputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFileButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFileButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output directory (Drag and drop supported)"));

        outputDirectory.setEditable(false);
        this.outputDirectory.setTransferHandler(new FileDragAndDrop() {
            @Override
            public boolean process(List<File> files) {
                File first = files.get(0);
                if (first.isDirectory()) {
                    setOutputDirectory(first);
                } else {
                    Toolkit.getDefaultToolkit().beep();
                }
                return true;
            }
        });

        outputDirectoryButton.setText("...");
        outputDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputDirectoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputDirectory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputDirectoryButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputDirectoryButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decryptWithAPassword.setText("Decrypt with a password:");
        decryptWithAPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptWithAPasswordActionPerformed(evt);
            }
        });

        passwordField.setEnabled(false);

        showPasswordField.setText("Show");
        showPasswordField.setEnabled(false);
        showPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordFieldActionPerformed(evt);
            }
        });

        extractButton.setText("Extract");
        extractButton.setEnabled(false);
        extractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractButtonActionPerformed(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(decryptWithAPassword)
                        .addGap(0, 233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPasswordField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(settingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(extractButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(decryptWithAPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extractButton)
                    .addComponent(settingsButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            setInputFile(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_inputFileButtonActionPerformed

    private void outputDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputDirectoryButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            setOutputDirectory(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_outputDirectoryButtonActionPerformed

    private void decryptWithAPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptWithAPasswordActionPerformed
        boolean enabled = this.decryptWithAPassword.isSelected();
        this.passwordField.setEnabled(enabled);
        this.showPasswordField.setEnabled(enabled);
    }//GEN-LAST:event_decryptWithAPasswordActionPerformed

    private void showPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordFieldActionPerformed
        if (this.showPasswordField.isSelected()) {
            this.passwordField.setEchoChar('\0');
        } else {
            this.passwordField.setEchoChar(new JPasswordField().getEchoChar());
        }
    }//GEN-LAST:event_showPasswordFieldActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        SettingsDialog dialog = new SettingsDialog(this, true);
        dialog.selectExtractTab();
        dialog.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void extractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractButtonActionPerformed
        char[] password = null;
        if (this.decryptWithAPassword.isSelected()) {
            password = this.passwordField.getPassword();
            if (password.length == 0) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Password is empty", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        ExtractOperation operation;
        try {
            this.passwordField.setText("");
            
            Path in = Path.of(this.inputFile.getText());
            Path out = Path.of(this.outputDirectory.getText());
            
            ExtractOperationSettings settings = new ExtractOperationSettings();
            settings.load();
            ExtractOperationData data = new ExtractOperationData(settings, in, out, password);
            try {
                if (getParent() instanceof Dialog d) {
                    operation = new ExtractOperation(data, d, true);
                } else if (getParent() instanceof Frame f) {
                    operation = new ExtractOperation(data, f, true);
                } else {
                    operation = new ExtractOperation(data, (Frame) null, true);
                }
            } finally {
                data.clearPassword();
            }
        } finally {
            if (password != null) {
                Arrays.fill(password, '\0');
            }
        }
        
        setVisible(false);
        dispose();
        
        if (this.auto) {
            operation.setCloseAfterFinishEnabled(true);
        }
        operation.start();
        operation.setVisible(true);
    }//GEN-LAST:event_extractButtonActionPerformed
    
    protected void auto(Path input, Path output, boolean encrypted) {
        this.inputFile.setText(input.toString());
        this.outputDirectory.setText(output.toString());
        if (encrypted) {
            this.decryptWithAPassword.doClick();
        }
        this.extractButton.setEnabled(true);
        this.auto = true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox decryptWithAPassword;
    private javax.swing.JButton extractButton;
    private javax.swing.JTextField inputFile;
    private javax.swing.JButton inputFileButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField outputDirectory;
    private javax.swing.JButton outputDirectoryButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton settingsButton;
    private javax.swing.JCheckBox showPasswordField;
    // End of variables declaration//GEN-END:variables
}
