/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.jmultidiskzip.ui.gui;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Future;
import javax.swing.SwingUtilities;
import matinilad.jmultidiskzip.ui.UIUtils;

/**
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public abstract class ProgressDialog extends javax.swing.JDialog {

    private String fileName = "Filename";
    private long fileProgress = 0;
    private long fileSize = 0;

    private long lastFileUpdateProgress = 0;
    private long lastFileUpdateTime = System.nanoTime();

    private Future<?> fileStatusUpdate = null;

    private long totalInputCount = 0;
    private long totalOutputCount = 0;
    private long partSize = -1;
    private boolean reverseCompressionRatio = false;

    private Future<?> statusUpdate = null;

    private int errors = 0;
    
    private Thread thread = null;
    
    public ProgressDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        clearComponents();
        setLocationRelativeTo(parent);
    }

    public ProgressDialog(java.awt.Dialog dialog, boolean modal) {
        super(dialog, modal);
        initComponents();
        clearComponents();
        setLocationRelativeTo(dialog);
    }

    private void clearComponents() {
        this.filenameField.setText("");
        this.progressBar.setValue(0);
        this.progressBarLabel.setText(String.format("%.2f", 0f) + "%");
        this.sizeField.setText(UIUtils.formatBytesShort(0) + " of " + UIUtils.formatBytes(0));
        this.speedField.setText(UIUtils.formatBytesShort(0) + "/s");
        this.estimatedTimeField.setText(UIUtils.formatCountdownSeconds(0));
        this.totalInputField.setText(UIUtils.formatBytes(0));
        this.totalOutputField.setText(UIUtils.formatBytes(0));
        this.compressionRatioField.setText(String.format("%.2f", 0f) + "%");
        this.partCountField.setText("");
        this.logErrorsLabel.setText("Log (0 Errors):");
        this.logTextArea.setText("");
        this.cancelButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filenameField = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        progressBarLabel = new javax.swing.JLabel();
        speedField = new javax.swing.JTextField();
        sizeField = new javax.swing.JTextField();
        estimatedTimeField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalInputField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compressionRatioField = new javax.swing.JTextField();
        totalOutputField = new javax.swing.JTextField();
        logErrorsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        partCountField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Title goes here");
        setMinimumSize(new java.awt.Dimension(250, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Current file status"));

        filenameField.setEditable(false);
        filenameField.setText("Filename");
        filenameField.setBorder(null);

        progressBar.setMaximum(10000);

        progressBarLabel.setText("100.00%");

        speedField.setEditable(false);
        speedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        speedField.setText("100 MiB/s");
        speedField.setBorder(null);

        sizeField.setEditable(false);
        sizeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sizeField.setText("568 GiB of 48979 GiB");
        sizeField.setBorder(null);

        estimatedTimeField.setEditable(false);
        estimatedTimeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        estimatedTimeField.setText("10m10s estimated");
        estimatedTimeField.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filenameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estimatedTimeField)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBarLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sizeField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estimatedTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        jLabel1.setText("Total (Input):");

        totalInputField.setEditable(false);
        totalInputField.setText("100 MiB");
        totalInputField.setBorder(null);

        jLabel2.setText("Total (Output):");

        jLabel3.setText("Compression Ratio:");

        compressionRatioField.setEditable(false);
        compressionRatioField.setText("100.00%");
        compressionRatioField.setBorder(null);

        totalOutputField.setEditable(false);
        totalOutputField.setText("100 MiB");
        totalOutputField.setBorder(null);

        logErrorsLabel.setText("Log (0 Errors):");

        logTextArea.setEditable(false);
        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addComponent(logErrorsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compressionRatioField)
                            .addComponent(totalOutputField)
                            .addComponent(totalInputField))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalOutputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(compressionRatioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logErrorsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        partCountField.setEditable(false);
        partCountField.setText("10 Parts of 1MiB + 1 Part of 5 KiB");
        partCountField.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(partCountField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(partCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (this.thread != null) {
            this.thread.interrupt();
            this.logTextArea.append("Sent cancel signal\n");
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        Objects.requireNonNull(fileName, "fileName is null");
        this.fileName = fileName;
    }

    public long getFileProgress() {
        return fileProgress;
    }

    public void setFileProgress(long fileProgress) {
        if (fileProgress < 0) {
            throw new IllegalArgumentException("fileProgress < 0");
        }
        if (fileProgress > getFileSize()) {
            throw new IllegalArgumentException("fileProgress > getFileSize()");
        }
        if (fileProgress < getFileProgress()) {
            throw new IllegalArgumentException("fileProgress < getFileProgress()");
        }
        this.fileProgress = fileProgress;
    }

    public long getFileSize() {
        return fileSize;
    }

    public void setFileSize(long fileSize) {
        if (fileSize < 0) {
            throw new IllegalArgumentException("fileSize < 0");
        }
        this.fileSize = fileSize;
        this.fileProgress = 0;
        this.lastFileUpdateProgress = 0;
        this.lastFileUpdateTime = System.nanoTime();
    }

    public boolean updateFileStatus(boolean force) {
        if (!force && this.fileStatusUpdate != null && !this.fileStatusUpdate.isDone()) {
            return false;
        }

        List<Runnable> toRun = new ArrayList<>();

        final String newName = getFileName();
        final String newSizeField = UIUtils.formatBytesShort(getFileProgress()) + " of " + UIUtils.formatBytesShort(getFileSize());

        double progress = (getFileProgress() / ((double) getFileSize())) * 100.0;
        if (!Double.isFinite(progress)) {
            progress = 0.0;
        }

        final int progressInt = (int) (progress * 100.0);
        final String newProgressLabel = String.format("%.2f", progress) + "%";

        Runnable updateFile = () -> {
            this.filenameField.setText(newName);
            this.sizeField.setText(newSizeField);
            this.progressBar.setValue(progressInt);
            this.progressBarLabel.setText(newProgressLabel);
        };
        toRun.add(updateFile);

        double timePassed = (System.nanoTime() - this.lastFileUpdateTime) / 1E9d;
        if (timePassed >= 1.0) {
            long bytesProcessed = getFileProgress() - this.lastFileUpdateProgress;

            double transferSpeed = bytesProcessed / timePassed;
            double estimatedTime = (getFileSize() - getFileProgress()) / transferSpeed;

            this.lastFileUpdateTime = System.nanoTime();
            this.lastFileUpdateProgress = getFileProgress();

            final String newTransferSpeed = UIUtils.formatBytesShort((long) transferSpeed) + "/s";
            final String newEstimatedTime = UIUtils.formatCountdownSeconds((long) estimatedTime);

            Runnable updateTime = () -> {
                this.speedField.setText(newTransferSpeed);
                this.estimatedTimeField.setText(newEstimatedTime);
            };
            toRun.add(updateTime);
        }

        if (force) {
            CompletableFuture<Void> completableFuture = new CompletableFuture<>();
            SwingUtilities.invokeLater(() -> {
                try {
                    for (Runnable r : toRun) {
                        r.run();
                    }
                } finally {
                    completableFuture.complete(null);
                }
            });
            this.fileStatusUpdate = completableFuture;
        } else {
            this.fileStatusUpdate = CompletableFuture.runAsync(() -> {
                try {
                    SwingUtilities.invokeAndWait(() -> {
                        for (Runnable r : toRun) {
                            r.run();
                        }
                    });
                } catch (InterruptedException | InvocationTargetException ex) {
                    //ignored
                }
            });
        }
        return true;
    }

    public void setTotalInputCount(long totalInputCount) {
        if (totalInputCount < 0) {
            throw new IllegalArgumentException("totalInputCount < 0");
        }
        this.totalInputCount = totalInputCount;
    }

    public long getTotalInputCount() {
        return totalInputCount;
    }

    public void setTotalOutputCount(long totalOutputCount) {
        if (totalOutputCount < 0) {
            throw new IllegalArgumentException("totalOutputCount < 0");
        }
        this.totalOutputCount = totalOutputCount;
    }

    public long getTotalOutputCount() {
        return totalOutputCount;
    }

    public void setReverseCompressionRatio(boolean reverseCompressionRatio) {
        this.reverseCompressionRatio = reverseCompressionRatio;
    }

    public boolean isReverseCompressionRatio() {
        return reverseCompressionRatio;
    }

    public long getPartSize() {
        return partSize;
    }

    public void setPartSize(long partSize) {
        if (partSize < 0) {
            partSize = -1;
        }
        if (partSize == 0) {
            throw new IllegalArgumentException("partSize == 0");
        }
        this.partSize = partSize;
    }

    public boolean updateStatus(boolean force) {
        if (!force && this.statusUpdate != null && !this.statusUpdate.isDone()) {
            return false;
        }

        long input = getTotalInputCount();
        long output = getTotalOutputCount();
        long part = getPartSize();

        final String newTotalInput = UIUtils.formatBytes(input);
        final String newTotalOutput = UIUtils.formatBytes(output);

        double compressionRatio = output / ((double) input);
        if (isReverseCompressionRatio()) {
            compressionRatio = 1.0 / compressionRatio;
        }
        if (!Double.isFinite(compressionRatio)) {
            compressionRatio = 0.0;
        }

        final String newCompressionRatio = String.format("%.2f", compressionRatio) + "%";

        final String newPartCount;
        if (part > 0) {
            long parts = output / part;
            long remainder = output - (parts * part);

            String partCount = "";
            if (parts != 0) {
                partCount += parts + (parts == 1 ? " Part" : " Parts") + " of " + UIUtils.formatBytes(part);
                if (remainder != 0) {
                    partCount += " + ";
                }
            }
            if (remainder != 0) {
                partCount += "1 Part of " + UIUtils.formatBytes(remainder);
            }

            newPartCount = partCount;
        } else {
            newPartCount = "";
        }

        Runnable updateTask = () -> {
            this.totalInputField.setText(newTotalInput);
            this.totalOutputField.setText(newTotalOutput);
            this.compressionRatioField.setText(newCompressionRatio);
            this.partCountField.setText(newPartCount);
        };

        if (force) {
            CompletableFuture<Void> completableFuture = new CompletableFuture<>();
            SwingUtilities.invokeLater(() -> {
                try {
                    updateTask.run();
                } finally {
                    completableFuture.complete(null);
                }
            });
            this.statusUpdate = completableFuture;
        } else {
            this.statusUpdate = CompletableFuture.runAsync(() -> {
                try {
                    SwingUtilities.invokeAndWait(() -> {
                        updateTask.run();
                    });
                } catch (InterruptedException | InvocationTargetException ex) {
                    //ignored
                }
            });
        }
        return true;
    }

    public int getErrors() {
        return errors;
    }

    public void incrementErrors(int toIncrement) {
        if (toIncrement == 0) {
            return;
        }
        if (toIncrement < 0) {
            throw new IllegalArgumentException("toIncrement < 0");
        }
        this.errors += toIncrement;

        int err = this.errors;
        final String newLogErrorsLabel = "Log (" + err + " " + (err == 1 ? "Error" : "Errors") + "):";
        SwingUtilities.invokeLater(() -> {
            this.logErrorsLabel.setText(newLogErrorsLabel);
        });
    }
    
    public void print(String text) {
        SwingUtilities.invokeLater(() -> {
            this.logTextArea.append(text);
        });
    }
    
    public void println(String text) {
        SwingUtilities.invokeLater(() -> {
            this.logTextArea.append(text);
            this.logTextArea.append("\n");
        });
    }
    
    public void start() {
        if (this.thread != null) {
            throw new UnsupportedOperationException("already running");
        }
        clearComponents();
        this.thread = new Thread(() -> {
            try {
                try {
                    ProgressDialog.this.run();
                } catch (Throwable t) {
                    ProgressDialog.this.incrementErrors(1);
                    ProgressDialog.this.print(UIUtils.stacktraceOf(t));
                }
            } finally {
                SwingUtilities.invokeLater(() -> {
                    this.logTextArea.append("Finished\n");
                    this.cancelButton.setEnabled(false);
                    this.thread = null;
                });
            }
        });
        this.thread.setDaemon(true);
        this.thread.start();
        
        this.cancelButton.setEnabled(true);
    }
    
    public boolean isRunning() {
        return this.thread != null;
    }
    
    public abstract void run() throws Throwable;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField compressionRatioField;
    private javax.swing.JTextField estimatedTimeField;
    private javax.swing.JTextField filenameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logErrorsLabel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JTextField partCountField;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressBarLabel;
    private javax.swing.JTextField sizeField;
    private javax.swing.JTextField speedField;
    private javax.swing.JTextField totalInputField;
    private javax.swing.JTextField totalOutputField;
    // End of variables declaration//GEN-END:variables
}
